services:
  grafana:
    image: grafana/grafana:latest
    container_name: my_cool_app_grafana
    ports:
      - '3000:3000'
    networks:
      - my_cool_app_network
    depends_on:
      - promtail
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: my_cool_app_loki
    restart: always
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - '3100:3100'
    volumes:
      - ./config/loki:/etc/loki
      - loki_data:/loki
    networks:
      - my_cool_app_network

  promtail:
    image: grafana/promtail:latest
    container_name: my_cool_app_promtail
    restart: always
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - /var/log:/var/log
      - ./config/promtail:/etc/promtail
    networks:
      - my_cool_app_network

networks:
  my_cool_app_network:
    driver: bridge

volumes:
  loki_data:
    driver: local
  grafana_data:
    driver: local
